# Reference: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 1

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
      time: '07:00' # UTC

  # Maintain dependencies for terraform
  - package-ecosystem: 'terraform'
    directory: '/'
    schedule:
      interval: 'monthly' # daily, weekly, monthly
      day: 'monday'
      time: '07:00' # UTC

    open-pull-requests-limit: 50 # Allow up to 50 open pull requests

    # Create a group of dependencies to be updated together in one pull request
    groups:
      # Specify a name for the group, which will be used in pull request titles and branch names
      non-major-deps:
        # Define patterns to include dependencies in the group (based on dependency name)
        patterns:
          - '*' # A wildcard that matches all dependencies in the package (may open a large pull request)
        update-types: # Exclude major version updates from group
          - 'minor'
          - 'patch'
